#!/usr/bin/env python3
"""One-off: EN index.html -> SV. Run from repo root: python3 landing/tools/sv_translate_index.py"""
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
src = (ROOT / "en" / "index.html").read_text(encoding="utf-8")

# Longest-first to avoid partial matches
REPL = [
    ("Web-Engenharia officially announces the start of a new phase. We are developing robust internal solutions\n            that, after production validation, will be launched as commercial products for up to 2 years. After this\n            cycle, projects will be released as Open Source, allowing other companies to offer them as a service, with\n            community support.",
     "Web-Engenharia meddelar officiellt starten av en ny fas. Vi utvecklar robusta interna lösningar\n            som, efter validering i produktion, kommer att lanseras som kommersiella produkter i upp till två år. Efter denna\n            cykel släpps projekten som öppen källkod, så att andra företag kan erbjuda dem som tjänst med\n            community-stöd."),
    ("Access to environments with least-privilege principle; secrets and credentials under secure management",
     "Åtkomst till miljöer enligt minsta behörighet; hemligheter och inloggningsuppgifter hanteras säkert"),
    ("Response SLA defined in retainer contracts; audit trail for integrations with sensitive data",
     "Svarstids-SLA enligt retainer-avtal; revisionsspår för integrationer med känslig data"),
    ("As software developers we strive to deliver not only well-written code, but code that delivers real\n                value to every client. Have not just a good web application in production, but also improve your\n                software processes and quality assurance.",
     "Som mjukvaruutvecklare strävar vi efter att leverera inte bara välskriven kod, utan kod som ger verkligt\n                värde för varje kund — inte bara en bra webbapplikation i drift, utan också förbättrade\n                utvecklingsprocesser och kvalitetssäkring."),
    ("Engineering applied to integrations:</span>\n                versioned contracts, idempotency patterns, and observability from the first sprint — ready for\n                regulated environments and high load.",
     "Teknik tillämpad på integrationer:</span>\n                versionskontrakt, idempotensmönster och observerbarhet från första sprinten — redo för\n                reglerade miljöer och hög belastning."),
    ("From discovery to go-live: resilient integrations, clear contracts, and operation with audit trail —\n              without relying on fragile point-to-point shortcuts.",
     "Från discovery till driftsättning: resilienta integrationer, tydliga avtal och drift med revisionsspår —\n              utan sköra punkt-till-punkt-genvägar."),
    ("Unite systems and data with clear architecture, making integrations accessible, useful and lower-risk for the business.",
     "Förena system och data med tydlig arkitektur och gör integrationer tillgängliga, användbara och mindre riskfyllda för verksamheten."),
    ("A world where resilient, well-governed integrations expand opportunity, reduce technical risk and sustain continuous operation.",
     "En värld där resilienta, välstyrda integrationer skapar möjligheter, minskar teknisk risk och upprätthåller kontinuerlig drift."),
    ("Remote-first, engineering with purpose. Our greatest product is people: we value talent, transparency and growth.",
     "Remote-first, teknik med syfte. Vår viktigaste produkt är människor: vi värdesätter talang, transparens och utveckling."),
    ("Inspired by practices and public statements from companies such as Google, Ericsson and Meta.",
     "Inspirerad av praxis och offentliga uttalanden från bland annat Google, Ericsson och Meta."),
    ("We identify the best model for your context: team reinforcement, full project, or capacity building.",
     "Vi identifierar den bästa modellen för ert sammanhang: förstärkning av team, helprojekt eller kompetensuppbyggnad."),
    ("Your team may be overloaded with demands, affecting delivery dates. The best approach is to divide and\n                conquer. Let your team focus on specific objectives and call us to help with new features, extensions,\n                maintenance, and more.",
     "Ert team kan vara överbelastat, vilket påverkar leveransdatum. Bästa vägen är att fördela arbetet:\n                låt teamet fokusera på utvalda mål och anlita oss för nya funktioner, utökningar,\n                underhåll med mera."),
    ("We provide cost estimates and delivery forecasts, then work on implementation using agile best\n                practices. Scope is variable and we frequently reassess what should be built, so you get the software\n                you really need at the end of the project.",
     "Vi ger kostnadsuppskattningar och leveransprognoser och genomför implementation med agila\n                arbetssätt. Omfattningen kan variera och vi omvärderar ofta vad som ska byggas, så att ni får den mjukvara\n                ni verkligen behöver i slutet av projektet."),
    ("We bring you a team of skilled professionals to help develop your projects. We also offer programming\n                courses so you can grow in other languages and technologies.",
     "Vi tar med ett team av erfarna personer som hjälper till att utveckla era projekt. Vi erbjuder också programmeringskurser\n                så att ni kan växa inom fler språk och tekniker."),
    ("Flexibility for your context: hourly rate, fixed price, retainer, shared success, and special cases.",
     "Flexibilitet för ert sammanhang: timtaxa, fast pris, retainer, delad framgång och särskilda fall."),
    ("Billing per hour worked. Time &amp; Materials, ideal for variable scope and exploratory sprints.",
     "Fakturering per arbetad timme. Time &amp; Materials, lämpligt vid varierande omfattning och utforskande sprinter."),
    ("Fixed fee with defined scope and schedule. Predictability for client and consultant.",
     "Fast arvode med definierad omfattning och tidplan. Förutsägbarhet för kund och konsult."),
    ("PMO as a Service or ongoing consulting. Recurring availability and predictable revenue.",
     "PMO som tjänst eller löpande rådgivning. Återkommande tillgänglighet och förutsägbara intäkter."),
    ("Compensation tied to goals. Success fee when pre-defined objectives are achieved.",
     "Ersättning kopplad till mål. Success fee när fördefinierade mål uppnås."),
    ("Progressive equity participation. Equity with cliff and calendar for long-term partnerships.",
     "Stegvis ägarandel. Aktier med cliff och tidsplan för långsiktiga partnerskap."),
    ("Voluntary or subsidized work for social impact, ESG causes, and community capacity building.",
     "Ideellt eller subventionerat arbete för social påverkan, ESG och kompetensuppbyggnad i samhället."),
    ("Combination of models: retainer + success fee, hourly + vesting, according to maturity and profile.",
     "Kombination av modeller: retainer + success fee, timme + vesting, utifrån mognad och profil."),
    ("Integrations and API-first architecture in four pillars, plus project management and IT governance\n            consulting — each block translates technical capability into business results.",
     "Integrationer och API-first-arkitektur i fyra pelare, plus projektledning och rådgivning inom IT-styrning —\n            varje block omsätter teknisk förmåga till affärsresultat."),
    ("System and contract mapping; non-functional requirements (latency, idempotency, resilience); patterns\n                (API gateway, messaging, CDC). Goal: less rework and surprises in production.",
     "Kartläggning av system och kontrakt; icke-funktionella krav (latens, idempotens, resiliens); mönster\n                (API-gateway, meddelanden, CDC). Mål: mindre omarbetning och överraskningar i produktion."),
    ("Connectors, REST APIs and events, orchestration and on-demand iPaaS, ETL and streaming. Goal: delivery\n                that scales with the business.",
     "Kopplingar, REST-API:er och händelser, orkestrering och iPaaS vid behov, ETL och streaming. Mål: leverans\n                som skalar med verksamheten."),
    ("SLIs/SLOs for integrations, monitoring, runbooks, and incident management across vendors and internal\n                teams. We treat integration as product — not as an isolated script.",
     "SLI/SLO för integrationer, övervakning, runbooks och incidenthantering över leverantörer och interna\n                team. Vi betraktar integration som produkt — inte som ett isolerat skript."),
    ("OAuth/OIDC, secrets, mTLS when applicable, living documentation (OpenAPI, event catalog), and audit\n                trail. Security and compliance by design, not as an afterthought.",
     "OAuth/OIDC, hemligheter, mTLS vid behov, levande dokumentation (OpenAPI, händelsekatalog) och revisionsspår.\n                Säkerhet och regelefterlevnad inbyggt från början."),
    ("Maturity assessment with OPM3 and ITIL. Process and effectiveness audit (not just compliance).\n                Deliverable: Improvement Program with identified gaps and evolution roadmap.",
     "Mognadsbedömning med OPM3 och ITIL. Granskning av processer och effekt (inte bara regelefterlevnad).\n                Leverans: förbättringsprogram med identifierade luckor och utvecklingsplan."),
    ("Project Office implementation (PMO Lite to Full, or Agile). Strategic prioritization, EVM, and\n                initiative selection. Performance metrics, dashboards, and PMO as a Service.",
     "Införande av projektkontor (PMO Lite till Full eller Agile). Strategisk prioritering, EVM och\n                urval av initiativ. Nyckeltal, dashboards och PMO som tjänst."),
    ("Incident, change, problem, and asset management (CMDB). Platform implementation (ServiceNow,\n                Jira SM, GLPi), self-service portals, and automated approval workflows.",
     "Incident-, ändrings-, problem- och tillgångshantering (CMDB). Plattformsimplementation (ServiceNow,\n                Jira SM, GLPi), självbetjäningsportaler och automatiserade godkännandeflöden."),
    ("Waterfall, Scrum, Kanban, and hybrid models per context. EVM, CAPEX/OPEX management,\n                procurement and contracts. Engineering and infrastructure projects with industrial risk management.",
     "Vattenfall, Scrum, Kanban och hybridmodeller efter kontext. EVM, CAPEX/OPEX-hantering,\n                upphandling och avtal. Teknik- och infrastrukturprojekt med industriell riskhantering."),
    ("Applied artificial intelligence capabilities: from integrating models into your systems to computer vision, tailored training, and data analysis for evidence-based decision-making.",
     "Tillämpad AI: från att integrera modeller i era system till datorseende, skräddarsydd träning och dataanalys för beslut underbyggda av data."),
    ("APIs, events, and orchestration to connect AI models to existing systems (ERP, CRM, data); pipelines and data governance at the edge.",
     "API:er, händelser och orkestrering för att koppla AI-modeller till befintliga system (ERP, CRM, data); pipelines och datastyrning vid kanten."),
    ("Detection, classification, and image/video analysis solutions; models tailored to industrial use cases, quality, and operations.",
     "Detektering, klassificering och bild-/videoanalys; modeller anpassade till industriella fall, kvalitet och drift."),
    ("ML pipeline design (data, feature store, training and evaluation); fine-tuning and optimization for business-specific scenarios.",
     "Utformning av ML-pipelines (data, feature store, träning och utvärdering); finjustering och optimering för verksamhetsspecifika scenarier."),
    ("Data exploration, cleaning, and modeling; dashboards, reporting, and evidence-based decision-making; preparation for ML/AI.",
     "Datautforskning, städning och modellering; dashboards, rapportering och beslut underbyggda av data; förberedelse för ML/AI."),
    ("Integration projects where we delivered mapping, architecture, and implementation — with measurable results.",
     "Integrationsprojekt där vi levererat kartläggning, arkitektur och implementation — med mätbara resultat."),
    ("Legacy system without modern API blocked adoption of a new gateway. We delivered a REST layer with\n                stable contract, gradual migration, and transaction idempotency.",
     "Äldre system utan modern API hindrade införande av en ny gateway. Vi levererade ett REST-lager med\n                stabilt kontrakt, gradvis migrering och idempotenta transaktioner."),
    ("Multiple channels (store, marketplace, POS) failing on inventory sync. We mapped flows, designed\n                async events, and implemented orchestration with fallback and configurable retry.",
     "Flera kanaler (butik, marknadsplats, kassa) med bristande lagersynk. Vi kartlade flöden, designade\n                asynkrona händelser och implementerade orkestrering med fallback och konfigurerbar omkörning."),
    ("Client needed to expose stable APIs for integrators and white-label. Assessment of existing surfaces,\n                OpenAPI documentation, and version governance.",
     "Kunden behövde stabila API:er för integratörer och white label. Kartläggning av befintliga ytor,\n                OpenAPI-dokumentation och versionsstyrning."),
    ("HEEx component library for Elixir, inspired by Radix UI and ShadCN. Unified, modern, and reusable\n                look for all our products.",
     "HEEx-komponentbibliotek för Elixir, inspirerat av Radix UI och ShadCN. Enhetlig, modern och återanvändbar\n                design för alla våra produkter."),
    ("Internal system for managing our Web-Engenharia software engineers. Reusable modules: authentication,\n                document upload, time tracking, teams, and projects.",
     "Internt system för att hantera våra mjukvaruutvecklare. Återanvändbara moduler: autentisering,\n                dokumentuppladdning, tidrapportering, team och projekt."),
    ("Complete banking platform, from card issuance to payment processing. Modeled on experience with 8\n                traditional banks and 8 Brazilian digital banks. Built by those who understand the banking market\n                from the inside.",
     "Komplett bankplattform, från kortutgivning till betalningsflöden. Bygger på erfarenhet från 8\n                traditionella banker och 8 digitala banker i Brasilien. Byggt av de som förstår bankmarknaden\n                inifrån."),
    ("AI developed exclusively for internal Web-Engenharia use. Integrated with our collaboration platform.\n                This project will never be commercialized; our differentiator starts from within.",
     "AI utvecklad enbart för internt bruk hos Web-Engenharia. Integrerad med vår samarbetsplattform.\n                Projektet kommer inte att kommersialiseras; vår differentiering börjar inifrån."),
    ("Platform for group travel control and management.",
     "Plattform för att hantera och styra gruppresor."),
    ("ERP, Mobile Digital Super app (shopping, deliveries, bank cards), POS and payment processing machine\n                integrations.",
     "ERP, mobil digital superapp (handel, leveranser, bankkort), kassor och integrationer mot betalterminaler."),
    ("Web-Engenharia is made by developers. Our portfolio is our own talent — with care for intellectual\n              property, image rights, and professional appreciation of each team member.",
     "Web-Engenharia byggs av utvecklare. Vår portfölj är vår egen talang — med respekt för immateriella\n              rättigheter, bildrättigheter och professionellt erkännande av varje teammedlem."),
    ("From discovery to operation, with clear milestones and incremental deliveries.",
     "Från discovery till drift, med tydliga milstolpar och inkrementella leveranser."),
    ("Context alignment, system and risk inventory; definition of measurable success criteria.",
     "Samordning av kontext, inventering av system och risker; mätbara framgångskriterier."),
    ("API-first design, synchronous vs. event flows, decoupling, and data strategy.",
     "API-first-design, synkrona kontra händelsedrivna flöden, frikoppling och datastrategi."),
    ("Proof of concept when needed; incremental delivery with testing and observability from the start.",
     "Proof of concept vid behov; inkrementell leverans med test och observerbarhet från start."),
    ("Planned cutover, documented handover, and continuous operation agreements.",
     "Planerad övergång, dokumenterad överlämning och avtal för kontinuerlig drift."),
    ("We work where your data and processes already live: cloud, ERP, payments, and digital channels. Third-party\n            logos only with permission and per each brand's guideline.",
     "Vi arbetar där era data och processer redan finns: moln, ERP, betalningar och digitala kanaler. Tredjepartslogotyper\n            endast med tillstånd enligt respektive varumärkesriktlinjer."),
    ("We integrate via exposed APIs, webhooks, queues, and batch flows when the domain requires — always with\n            versioned contracts and production visibility.",
     "Vi integrerar via exponerade API:er, webhooks, köer och batchflöden när domänen kräver det — alltid med\n            versionskontrakt och synlighet i produktion."),
    ("Modernization and legacy coexistence are part of typical scope. References to Open Finance or regulated\n            arrangements are treated as integration technical layer, without replacing client legal counsel.",
     "Modernisering och samsyn med äldre system ingår ofta. Referenser till Open Finance eller reglerade upplägg\n            behandlas som tekniskt integrationslager och ersätter inte kundens juridiska rådgivning."),
    ("Yes. We work with data minimization, processing agreements when applicable, audit trails, and access\n                controls — always aligned with your legal team and DPO.",
     "Ja. Vi arbetar med dataminimering, personuppgiftsbiträdesavtal vid behov, revisionsspår och åtkomstkontroll\n                — alltid i linje med ert juridiska team och dataskyddsombud."),
    ("It depends on scope, legacy API maturity, and POC needs. After discovery we deliver a plan with\n                milestones — from weeks for focused MVPs to quarters for larger programs.",
     "Det beror på omfattning, mognad hos befintliga API:er och behov av POC. Efter discovery levererar vi en plan med\n                milstolpar — från veckor för fokuserade MVP till kvartal för större program."),
    ("Both: integration layers, BFF portals, automation, and evolution of existing systems — always with\n                focus on stable contracts and sustainable operation.",
     "Både och: integrationslager, BFF-portaler, automation och vidareutveckling av befintliga system — med fokus på\n                stabila kontrakt och hållbar drift."),
    ("Usually IT or architecture sponsors, with product close to business rules. When go-live depends on\n                vendors, we align rituals and responsibilities so cutover isn't held hostage by a single link.",
     "Vanligtvis IT- eller arkitektursponsorer med produkt nära affärsregler. När driftsättning beror på\n                leverantörer synkar vi ritualer och ansvar så att övergången inte fastnar i en enda länk."),
    ("We map available surfaces — files, databases, queues, scheduled exports, or UI automation when\n                unavoidable — and design secure integration layers. When it makes sense, gradual strangling in favor\n                of more stable contracts.",
     "Vi kartlägger tillgängliga ytor — filer, databaser, köer, schemalagda exporter eller UI-automation när det\n                inte går att undvika — och designar säkra integrationslager. Vid behov gradvis utbyggnad mot\n                stabilare kontrakt."),
    ("Predominantly remote, with synchronous ceremonies at agreed times. On-site visits and workshops\n                are available on demand and scope alignment.",
     "Huvudsakligen distans, med synkrona ceremonier vid avtalade tider. Besök på plats och workshopar\n                erbjuds vid behov och efter omfattningsavstämning."),
    ("Project by phases (discovery, implementation, operation), retainer for continuous evolution, or\n                a combination. Initial discovery enables estimate and milestone plan before larger commitments.\n                <a href=\"#modelos-contratacao\" class=\"mt-2 inline-block font-medium text-brand-mid underline hover:text-brand-dark\"\n                  >Learn about our engagement models</a\n                >.",
     "Projekt i faser (discovery, implementation, drift), retainer för löpande utveckling eller\n                en kombination. Inledande discovery möjliggör uppskattning och milstolpsplan före större åtaganden.\n                <a href=\"#modelos-contratacao\" class=\"mt-2 inline-block font-medium text-brand-mid underline hover:text-brand-dark\"\n                  >Läs om våra engagemangsmodeller</a\n                >."),
    ("Briefly describe the context (systems involved, urgency, constraints). We will reply with next steps\n                and, if it makes sense, an alignment call.",
     "Beskriv kort sammanhanget (system, brådska, begränsningar). Vi återkommer med nästa steg\n                och vid behov ett avstämningsmöte."),
    ("Describe your project, systems involved, urgency...",
     "Beskriv ert projekt, berörda system, brådska …"),
    ("We use cookies to ensure you get the best experience on our website.",
     "Vi använder cookies för att ge dig bästa möjliga upplevelse på vår webbplats."),
    ("Schedule a technical conversation",
     "Boka ett tekniskt samtal"),
    ("Less technical risk in integrations — with end-to-end API-first architecture",
     "Mindre teknisk risk i integrationer — med API-first-arkitektur från början till slut"),
    ("Software &amp; integrations", "Mjukvara och integrationer"),
    ("Skip to content", "Hoppa till innehåll"),
    ("Integration &amp; API-first Consulting", "Integration och API-first-rådgivning"),
    ("Your Software Development Consultancy - Web-Engenharia",
     "Er mjukvaruutvecklingspartner - Web-Engenharia"),
    ("B2B consulting in multi-technology integrations: clear contracts, operational governance, and reduced technical risk — from discovery to go-live.",
     "B2B-rådgivning inom integrationer i flera tekniker: tydliga avtal, operativ styrning och minskad teknisk risk — från discovery till driftsättning."),
    ('<html class="scroll-smooth" lang="en">', '<html class="scroll-smooth" lang="sv">'),
    ('<link rel="canonical" href="https://www.web-engenharia.com/en/" />',
     '<link rel="canonical" href="https://www.web-engenharia.com/sv/" />'),
    ('    <link rel="alternate" hreflang="kok" href="https://www.web-engenharia.com/kok/" />',
     '    <link rel="alternate" hreflang="kok" href="https://www.web-engenharia.com/kok/" />\n    <link rel="alternate" hreflang="sv" href="https://www.web-engenharia.com/sv/" />'),
    ('<meta property="og:locale" content="en" />',
     '<meta property="og:locale" content="sv_SE" />\n    <meta property="og:locale:alternate" content="pt_BR" />\n    <meta property="og:locale:alternate" content="en" />\n    <meta property="og:locale:alternate" content="es_ES" />\n    <meta property="og:locale:alternate" content="ja" />\n    <meta property="og:locale:alternate" content="kok" />'),
    ("Schedule a technical conversation. Multi-technology integrations with API-first design, from discovery to operation.",
     "Boka ett tekniskt samtal. Integrationer i flera tekniker med API-first-design, från discovery till drift."),
    ('content="Web-Engenharia — Integration & API-first Consulting"',
     'content="Web-Engenharia — integration och API-first-rådgivning"'),
]

# Apply longest-first within REPL (already ordered) then extra passes
for old, new in REPL:
    if old in src:
        src = src.replace(old, new)

# Second batch (shorter / overlapping-safe)
EXTRA = [
    ("Schedule a call", "Boka samtal"),
    ("View services", "Se tjänster"),
    ("Refresh the page to see another brand animation.",
     "Ladda om sidan för att se en annan varumärkesanimation."),
    ("We are Web-Engenharia", "Vi är Web-Engenharia"),
    ("+10 years", "+10 år"),
    ("in software", "i mjukvara"),
    ("Lean team", "Slankt team"),
    ("with integration expertise", "med integrationsexpertis"),
    ("Remote-first", "Remote-first"),
    ("— Brazil", "— Brasilien"),
    ("contract design", "kontraktsdesign"),
    ("from diagnosis to support", "från diagnos till support"),
    ("Culture, mission and principles", "Kultur, uppdrag och principer"),
    ("Mission", "Uppdrag"),
    ("Vision", "Vision"),
    ("Values", "Värderingar"),
    ("Principles", "Principer"),
    ("Culture", "Kultur"),
    ("Client focus", "Kundfokus"),
    ("Integrity", "Integritet"),
    ("Professionalism", "Professionalitet"),
    ("Perseverance", "Uthållighet"),
    ("Responsible innovation", "Ansvarsfull innovation"),
    ("Teamwork", "Teamarbete"),
    ("Clear, versioned contracts", "Tydliga, versionshanterade kontrakt"),
    ("Least privilege and governance", "Minsta behörighet och styrning"),
    ("Observability from day one", "Observerbarhet från dag ett"),
    ("Long-term impact", "Långsiktig påverkan"),
    ("What we do", "Vad vi gör"),
    ("Staff augmentation", "Resursförstärkning"),
    ("We identify the best team to help you achieve your goals.",
     "Vi sätter ihop rätt team för att hjälpa er nå era mål."),
    ("Ideal for companies with an established development team.",
     "Ideal för företag med ett etablerat utvecklingsteam."),
    ("Outsourcing", "Outsourcing"),
    ("Our team is responsible for the full development of your project.",
     "Vårt team ansvarar för hela utvecklingen av ert projekt."),
    ("Ideal for companies without an in-house development team available.",
     "Ideal för företag utan tillgängligt internt utvecklingsteam."),
    ("Training", "Utbildning"),
    ("We help you better understand what you need to achieve your goals.",
     "Vi hjälper er förstå vad ni behöver för att nå era mål."),
    ("Ideal for companies or individuals who want to develop skills in other languages.",
     "Ideal för företag eller individer som vill utveckla färdigheter i fler språk."),
    ("Engagement models", "Engagemangsmodeller"),
    ("Hourly rate (HT)", "Timtaxa (T&amp;M)"),
    ("Ideal for: projects with unpredictable demand or discovery phases.",
     "Lämpligt för: projekt med oförutsägbar efterfrågan eller discovery-faser."),
    ("Fixed price", "Fast pris"),
    ("Ideal for: well-defined scope and low requirement volatility.",
     "Lämpligt för: väl avgränsad omfattning och låg kravvolatilitet."),
    ("Subscription (Retainer)", "Prenumeration (Retainer)"),
    ("Ideal for: continuous governance, evolving integrations, or recurring support.",
     "Lämpligt för: löpande styrning, växande integrationer eller återkommande support."),
    ("Success fee", "Success fee"),
    ("Ideal for: projects with measurable ROI and win-win alignment.",
     "Lämpligt för: projekt med mätbar ROI och win-win."),
    ("Vesting (startups)", "Vesting (startups)"),
    ("Ideal for: early-stage startups, CTOs, and strategic advisors.",
     "Lämpligt för: tidiga startups, CTO:er och strategiska rådgivare."),
    ("Pro-bono", "Pro bono"),
    ("Ideal for: NGOs, impact initiatives, and strategic cause portfolios.",
     "Lämpligt för: ideella organisationer, impact-initiativ och strategiska satsningar."),
    ("Hybrid", "Hybrid"),
    ("Ideal for: commercial flexibility and risk alignment between parties.",
     "Lämpligt för: kommersiell flexibilitet och riskdelning mellan parter."),
    ("Service catalog", "Tjänstkatalog"),
    ("Integrations &amp; Architecture", "Integrationer och arkitektur"),
    ("Discovery &amp; design", "Discovery och design"),
    ("Implementation", "Implementation"),
    ("Operation", "Drift"),
    ("Governance", "Styrning och regelefterlevnad"),
    ("Project Management", "Projektledning"),
    ("Diagnostics &amp; maturity", "Diagnostik och mognad"),
    ("PMO &amp; portfolio management", "PMO och portföljstyrning"),
    ("ITSM &amp; service catalog", "ITSM och tjänstekatalog"),
    ("Methodologies &amp; capital projects", "Metoder och kapitalprojekt"),
    ("AI Projects", "AI-projekt"),
    ("Integrations", "Integrationer"),
    ("Computer vision", "Datorseende"),
    ("Model training", "Modellträning"),
    ("Data science &amp; analytics", "Data science och analys"),
    ("Cases &amp; results", "Kundcase och resultat"),
    ("Fintech / Payments", "Fintech / betalningar"),
    ("ERP integration with payment gateway", "ERP-integration med betalningsgateway"),
    ("Go-live in 8 weeks; zero duplicate incidents in the first 30 days.",
     "Driftsättning på 8 veckor; inga dubblettincidenter de första 30 dagarna."),
    ("Retail / E-commerce", "Detaljhandel / e-handel"),
    ("Multi-channel order and inventory orchestration", "Orkestrering av order och lager i flera kanaler"),
    ("80% reduction in inventory discrepancies after 2 months in production.",
     "80 % minskning av lageravvikelser efter två månader i drift."),
    ("SaaS B2B", "SaaS B2B"),
    ("API-first for partners and white-label", "API-first för partners och white label"),
    ("Partner program launch in 6 weeks with defined SLAs.",
     "Partnerprogram lanserat på 6 veckor med definierade SLA."),
    ("Portfolio projects", "Portföljprojekt"),
    ("Library / UI", "Bibliotek / UI"),
    ("Internal collaboration", "Internt samarbete"),
    ("Fintech", "Fintech"),
    ("Internal AI", "Intern AI"),
    ("Travel", "Resor"),
    ("Retail / ERP", "Detaljhandel / ERP"),
    ("Our greatest product? People.", "Vår viktigaste produkt? Människor."),
    ("View previous", "Föregående"),
    ("View next", "Nästa"),
    ("Shared innovation. Engineering with purpose. Web-Engenharia — because the future isn't built alone.",
     "Delad innovation. Teknik med syfte. Web-Engenharia — framtiden byggs inte ensam."),
    ("How we work", "Hur vi arbetar"),
    ("Discovery", "Discovery"),
    ("Architecture &amp; contracts", "Arkitektur och kontrakt"),
    ("POC &amp; implementation", "POC och implementation"),
    ("Go-live &amp; support", "Driftsättning och support"),
    ("Want to see this journey in your context?",
     "Vill ni se denna resa i er kontext?"),
    ("Schedule a conversation", "Boka ett samtal"),
    ("Stacks &amp; ecosystems", "Stackar och ekosystem"),
    ("Cloud (AWS, GCP, Azure)", "Moln (AWS, GCP, Azure)"),
    ("ERP &amp; back office", "ERP och back office"),
    ("APIs &amp; messaging", "API:er och meddelanden"),
    ("Payments &amp; Open Finance (technical)", "Betalningar och Open Finance (tekniskt)"),
    ("Observability &amp; security", "Observerbarhet och säkerhet"),
    ("Frequently asked questions", "Vanliga frågor"),
    ("Do you handle integrations with personal data (GDPR/LGPD)?",
     "Hanterar ni integrationer med personuppgifter (GDPR/LGPD)?"),
    ("What is the typical timeline for an integration project?",
     "Vad är den typiska tidsplanen för ett integrationsprojekt?"),
    ("Do you only integrate or also develop product?",
     "Integrerar ni bara eller utvecklar ni också produkt?"),
    ("Who is usually the focal point on the client side?",
     "Vem är vanligtvis kontaktpunkt på kundsidan?"),
    ("What about legacy systems without modern APIs?",
     "Hur gör ni med äldre system utan moderna API:er?"),
    ("Do you work remotely or on-site?",
     "Arbetar ni på distans eller på plats?"),
    ("What is the commercial model?",
     "Vilken är den kommersiella modellen?"),
    ("Name <span", "Namn <span"),
    ("Email <span", "E-post <span"),
    ("Company <span", "Företag <span"),
    ("(optional)", "(valfritt)"),
    ("Message <span", "Meddelande <span"),
    ("Your full name", "Ert fullständiga namn"),
    ("Your company", "Ert företag"),
    ("Send via WhatsApp", "Skicka via WhatsApp"),
    ("Privacy", "Integritet"),
    ("Terms", "Villkor"),
    ("Careers", "Karriär"),
    ("Contact", "Kontakt"),
    ("Email", "E-post"),
    ("Accept", "Godkänn"),
    ("Home", "Hem"),
    ("Open menu", "Öppna meny"),
    ("Menu mobile", "Mobilmeny"),
    ("Language selection", "Språkval"),
    ("Language", "Språk"),
    ("Principal", "Huvudmeny"),
    ("Footer", "Sidfot"),
    ("Confiança operacional", "Operativt förtroende"),
    ("More", "Mer"),
    ("Services", "Tjänster"),
    ("Overview", "Översikt"),
    ("Engagement models", "Engagemangsmodeller"),
    ("Assessment &amp; architecture", "Kartläggning och arkitektur"),
    ("Implementation &amp; APIs", "Implementation och API:er"),
    ("Modernization &amp; cloud", "Modernisering och moln"),
    ("Operation &amp; observability", "Drift och observerbarhet"),
    ("Governance &amp; security", "Styrning och säkerhet"),
    ("AI Projects", "AI-projekt"),
    ("Stacks", "Stackar"),
    ("Cases", "Case"),
    ("Projects", "Projekt"),
    ("Culture", "Kultur"),
]

for old, new in sorted(EXTRA, key=lambda x: -len(x[0])):
    src = src.replace(old, new)

# Header language dropdown: keep SV labels in sync with en/index.html (dropdown list from main.js)
# After EXTRA, aria-label is already "Språkval" (from "Language selection" → "Språkval").
old_nav = """          <nav class="header-dropdown group relative px-1" data-dropdown="lang" aria-label="Språkval">
            <button
              type="button"
              id="lang-menu-btn"
              class="nav-link flex items-center gap-1 rounded-lg px-3 py-2.5 text-sm font-medium text-brand-dark/80 transition-colors hover:bg-brand-pulse/40 hover:text-brand-dark"
              aria-expanded="false"
              aria-haspopup="true"
              aria-controls="lang-menu-desktop"
            >
              <span id="lang-menu-btn-label">EN</span>
              <svg class="h-4 w-4 text-brand-mid transition-transform group-data-[open=true]:rotate-180" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <div
              id="lang-menu-desktop"
              class="absolute right-0 top-full z-50 mt-1 hidden min-w-[14rem] rounded-xl border border-brand-circuit/40 bg-white py-2 shadow-xl"
              role="menu"
            ></div>
          </nav>"""

new_nav = """          <nav class="header-dropdown group relative px-1" data-dropdown="lang" aria-label="Språkval">
            <button
              type="button"
              id="lang-menu-btn"
              class="nav-link flex items-center gap-1 rounded-lg px-3 py-2.5 text-sm font-medium text-brand-dark/80 transition-colors hover:bg-brand-pulse/40 hover:text-brand-dark"
              aria-expanded="false"
              aria-haspopup="true"
              aria-controls="lang-menu-desktop"
            >
              <span id="lang-menu-btn-label">SV</span>
              <svg class="h-4 w-4 text-brand-mid transition-transform group-data-[open=true]:rotate-180" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
              </svg>
            </button>
            <div
              id="lang-menu-desktop"
              class="absolute right-0 top-full z-50 mt-1 hidden min-w-[14rem] rounded-xl border border-brand-circuit/40 bg-white py-2 shadow-xl"
              role="menu"
            ></div>
          </nav>"""

if old_nav in src:
    src = src.replace(old_nav, new_nav)

# Mobile lang heading (language list is filled by main.js)
src = src.replace(
    '<p id="mobile-lang-label" class="mb-2 block text-xs font-semibold uppercase tracking-wide text-brand-mid">Language</p>',
    '<p id="mobile-lang-label" class="mb-2 block text-xs font-semibold uppercase tracking-wide text-brand-mid">Språk</p>',
)

# Script desenvolvedores
src = src.replace(
    '<script src="../js/desenvolvedores.en.js" defer></script>',
    '<script src="../js/desenvolvedores.sv.js" defer></script>',
)

(ROOT / "sv" / "index.html").write_text(src, encoding="utf-8")
print("Wrote", ROOT / "sv" / "index.html", "chars", len(src))
